### ISSUE TITLE
Variable number of labelers?

### ISSUE THREAD

**Issue by fedor57** [GoodDeeds/Fast-Dawid-Skene#1]
Hi, I tried to test the algorithm over some real-life data. I found the limitation of having a fixed number of labelers a little bit impractical. I wonder if this is a particular implementation limitation or one of the aggregation model? What if a user provide some kind of reasonable upper limit for a task labelers count (3-5-7)? Thank you!

**Comment by GoodDeeds** [comment]
Hi,
Thanks for your question. It is a limitation of the implementation, not of the model. We will update it to allow for a variable number of annotators per question.

**Comment by GoodDeeds** [comment]
Hi,
This has been updated in #2. Now, setting `k=0` or not setting `k` at all will make the algorithm use all available annotations for each data point.

Please re-open the issue if any problems persist. Thank you!

**Comment by fedor57** [comment]
Fantastic, thank you!!! Gonna test it and let you know!
